### ISSUE TITLE
Small complaint about Cypress .contain() wording

### ISSUE THREAD

**Issue by Jazzepi** [alexch/codelikethis#50]
http://codelikethis.com/lessons/javascript/cypress#anchor/multiple_matches

Contains a section talking about the .contains() operator for Cypress. The "result" column in the table there is correct, but I think the wording here.

`.contains( checks each individual element and succeeds if any contain the text`

is confusing .contains() is not an assertion, it's actually a sub-selector based on text. You can use it as a puesdo-assertion from the standpoint that cypress will flip out if it can't find an element, but generally you would never end a call chain with .contains() because you should be using it to skinny down the collection of dom elements. I think the text should mention something about the behavior of the subject that the .contains() call returns. I think it returns a cypress style collection of elements each of which matched the .contains() predicate, but I'd have to go check to make sure.

Maybe something like this.
`.contains( checks each individual element and returns the (first?) element if any contain the text`

**Comment by alexch** [comment]
I see wheee you’re coming from,  but I don’t think it’s misleading.

Earlier in the article (slideshow? presentation?) we say that every cypress
command contains a built-in assertion. This is a very good thing and should
be celebrated! The fact that contains() will fail if it finds no matches
means that it is an assertion; it also returns a collection for further
massaging or assertions down the line if necessary.

I could add a clarifying footnote (“remember, contains is both an assertion
and a matcher”) or something but in short, I’m not sure where you got the
idea that you would never end a chain with contains() — it seems like an
important feature of the Cypress DSL that “cy.contains(‘hello’)” is a valid
and complete scenario (the page must contain the string somewhere, else the
test fails).

The details around partial and multiple matches are still a little fuzzy
but I consider that a separate quirk.

-- 
Alex Chaffee - alexch@gmail.com
http://burlingtoncodeacademy.com
http://alexchaffee.com
http://codelikethis.com
http://twitter.com/alexch

**Comment by Jazzepi** [comment]
Not trying to be pedantic or nit-picky but part of the reason I brought up the difference between asserts, and navigational commands is that Cypress makes that distinction. If you look at the image below Cypress explicitly marks assertions as such, and leaves things like contains unmarked. To the untrained eye those .contains() are _not really_ assertions. They just happen to assert as a side effect.

![](https://i.imgur.com/JVYeOg2.png)

**Comment by alexch** [comment]
Hey, no worries -- I'm in favor of pedantic wild goose chases! :-) (It's even in my Twitter bio.)

I think I'm going to leave the wording as is because 
 * the point of that bullet is the word "any"
 * the description ("`.contains(` checks each individual element and succeeds if *any* contain the text")  is succinct and accurate -- I mean, it will fail if no elements contain it, so by definition it will succeed if any do
 * the word "assert" doesn't appear anywhere on the slide, so I don't think it's misleadingly blurring the difference between asserts and commands

but I will add a clarification point to the earlier `contains` slide, something like:

* returns a "chainer" for all matching elements, so you can do further assertions or refinements

Thanks for the feedback!
